#!/bin/sh

name=`basename $0`

homedir=~/.$name
log=$homedir/log
app_share=/usr/local/share/$name
cmd=$app_share/bin/$name
cron=$app_share/bin/$name.cron

pid_file=$log/$name.pid
cron_pid_file=$log/$name.cron.pid
arg_file=$log/$name.arg
stdout_log=$log/access.log
stderr_log=$log/error.err

# colors
green="\\033[1;32m"
default="\\033[0;39m"
red="\\033[1;31m"
pink="\\033[1;35m"
blue="\\033[1;34m"
white="\\033[0;02m"
yellow="\\033[1;33m"

get_pid() {
    cat "$pid_file"
}

get_cron_pid() {
    cat "$cron_pid_file"
}

get_arg() {
    cat "$arg_file"
}

is_running() {
    [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
}

is_cron_running() {
    [ -f "$cron_pid_file" ] && ps `get_cron_pid` > /dev/null 2>&1
}

case "$1" in

    start)
    if is_running; then
        echo "$yellow" "Already started"
    else
        arg=`get_arg`
        echo "$green" "Starting $name [" "$blue" "$arg" "$green]"
        [ ! -d $log ] && mkdir -p $log
        cd $homedir
        ulimit -n 65536 && $cmd $arg >> "$stdout_log" 2>> "$stderr_log" &
        echo "" > "$arg_file"
        echo $! > "$pid_file"
        $cron >/dev/null &
        echo $! > "$cron_pid_file"
        if ! is_running; then
            echo "$yellow" "Unable to start, see $stdout_log and $stderr_log"
            exit 1
        fi
    fi
    ;;

    stop)
    if is_running; then
        echo -n "$red" "Stopping $name.."
        kill -9 `get_pid` && kill -9 `get_cron_pid`
        for i in {1..10}; do
            if ! is_running;
                then break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "$yellow Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "$red>$default Application stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi

        if is_cron_running; then
            echo "$yellow Cron still running"
            exit 1
        else
            echo "$red>$default" "Cron stopped"
            if [ -f "$cron_pid_file" ]; then
                rm "$cron_pid_file"
            fi
        fi
        pkill notify-osd
        echo "$red>$default" "Notify OSD stopped"
    else
        echo "$default" "Not running"
    fi
    rm "$arg_file"
    ;;

    restart)
    $0 stop
    if is_running; then
        echo "$yellow" "Unable to stop, will not attempt to start"
        exit 1
    fi
    [ -d $log ] && echo "63" > "$arg_file"
    $0 start
    ;;

    status)
    if is_running; then
        pid=`get_pid`
        echo "$blue" "Git-Indicator" "$default" "App running with pid" "$green" "$pid"
    else
        echo "$red" "Stopped"
        exit 1
    fi
    if is_cron_running; then
        cront_pid=`get_cron_pid`
        echo "$blue" "Git-Indicator" "$default" "Cron running with pid" "$green" "$cront_pid"
    else
        echo "$red" "Stopped"
        exit 1
    fi
    ;;

    pid)
        pid=`get_pid`
        echo "$pid"
    ;;

    memory)
        while true
        do
            date=`date`
            app_pid=`get_pid`
            app_rss=`awk -F " " '/VmRSS/{ printf $2 }' /proc/$app_pid/status`
            app_vsz=`awk -F " " '/VmSize/{ printf $2 }' /proc/$app_pid/status`
            cron_pid=`get_cron_pid`
            cron_rss=`awk -F " " '/VmRSS/{ printf $2 }' /proc/$cron_pid/status`
            cron_vsz=`awk -F " " '/VmSize/{ printf $2 }' /proc/$cron_pid/status`
            echo "--- $yellow" "$date" "$default"
            echo "> $blue" "Application" "$default" ": VmSize=" "$green" "$app_vsz" "$default" "KiB / VmRSS=" "$green" "$app_rss" "$default" "KiB"
            echo "> $blue" "Cron" "$default" ": VmSize=" "$green" "$cron_vsz" "$default" "KiB / VmRSS=" "$green" "$cron_rss" "$default" "KiB"
            sleep 5
        done
    ;;

    access)
        cat "$stdout_log"
    ;;

    error)
        cat "$stderr_log"
    ;;

    *)
    echo "Usage: $0 {start|stop|restart|status|pid|memory|access|error}"
    exit 1
    ;;

esac

exit 0
